# http://travis-ci.org/#!/dailymuse/oz

language: python
matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27-tornado322
  - python: "2.7"
    env: TOXENV=py27-tornado401
  - python: "3.4"
    env: TOXENV=py34-tornado322
  - python: "3.4"
    env: TOXENV=py34-tornado401
  - python: "pypy"
    env: TOXENV=pypy-tornado322
  - python: "pypy"
    env: TOXENV=pypy-tornado401
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - pip install tox
script:
  - tox
services:
  - redis-server
