# http://travis-ci.org/#!/dailymuse/oz

language: python
install:
    - pip install tox
script:
    - tox
env:
    - TOXENV=py27-tornado322
    - TOXENV=py27-tornado401
    - TOXENV=py34-tornado322
    - TOXENV=py34-tornado401
    - TOXENV=pypy-tornado322
    - TOXENV=pypy-tornado401
